remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md
title: Seamless Healthcare Data Integration - Building an ETL Pipeline with FHIR APIs
description: This website showcases the development of an ETL pipeline for integrating healthcare data using FHIR APIs, highlighting practical use cases and technical solutions for seamless interoperability.
